insert into T_BRAND (ID, NAME) values ('BRD00001', 'ACER');
insert into T_BRAND (ID, NAME) values ('BRD00002', 'ADVANCE COMPUTER CORP');
insert into T_BRAND (ID, NAME) values ('BRD00003', 'AFOX');
insert into T_BRAND (ID, NAME) values ('BRD00004', 'AMAZON');
insert into T_BRAND (ID, NAME) values ('BRD00005', 'AMD-ADVANCED MICRO DEVICE');
insert into T_BRAND (ID, NAME) values ('BRD00006', 'AOC');
insert into T_BRAND (ID, NAME) values ('BRD00007', 'APC AMERICAN POWER CONVER');
insert into T_BRAND (ID, NAME) values ('BRD00008', 'ASROCK');
insert into T_BRAND (ID, NAME) values ('BRD00009', 'ASUS');
insert into T_BRAND (ID, NAME) values ('BRD00010', 'ASUS - COMERCIAL');
insert into T_BRAND (ID, NAME) values ('BRD00011', 'ASUS - CONSUMO');
insert into T_BRAND (ID, NAME) values ('BRD00012', 'BENQ');
insert into T_BRAND (ID, NAME) values ('BRD00013', 'BIT DEFENDER');
insert into T_BRAND (ID, NAME) values ('BRD00014', 'BOOMER');
insert into T_BRAND (ID, NAME) values ('BRD00015', 'BYTECC');
insert into T_BRAND (ID, NAME) values ('BRD00016', 'CAMBIUM NETWORKS');
insert into T_BRAND (ID, NAME) values ('BRD00017', 'CANON');
insert into T_BRAND (ID, NAME) values ('BRD00018', 'CORSAIR');
insert into T_BRAND (ID, NAME) values ('BRD00019', 'D-LINK');
insert into T_BRAND (ID, NAME) values ('BRD00020', 'DATTO');
insert into T_BRAND (ID, NAME) values ('BRD00021', 'DATTO CLOUD');
insert into T_BRAND (ID, NAME) values ('BRD00022', 'DELL');
insert into T_BRAND (ID, NAME) values ('BRD00023', 'DELL - COMERCIAL');
insert into T_BRAND (ID, NAME) values ('BRD00024', 'DELL - CONSUMO');
insert into T_BRAND (ID, NAME) values ('BRD00025', 'DELL - SERVIDORES');
insert into T_BRAND (ID, NAME) values ('BRD00026', 'DELTRON');
insert into T_BRAND (ID, NAME) values ('BRD00027', 'DISNEY');
insert into T_BRAND (ID, NAME) values ('BRD00028', 'EPSON');
insert into T_BRAND (ID, NAME) values ('BRD00029', 'ESET');
insert into T_BRAND (ID, NAME) values ('BRD00030', 'EVGA');
insert into T_BRAND (ID, NAME) values ('BRD00031', 'GEAR CHANNEL');
insert into T_BRAND (ID, NAME) values ('BRD00032', 'GENIUS');
insert into T_BRAND (ID, NAME) values ('BRD00033', 'GIGABYTE');
insert into T_BRAND (ID, NAME) values ('BRD00034', 'GOOGLE');
insert into T_BRAND (ID, NAME) values ('BRD00035', 'GRANDSTREAM');
insert into T_BRAND (ID, NAME) values ('BRD00036', 'HIKVISION');
insert into T_BRAND (ID, NAME) values ('BRD00037', 'HP');
insert into T_BRAND (ID, NAME) values ('BRD00038', 'IBM');
insert into T_BRAND (ID, NAME) values ('BRD00039', 'INTEL CORP');
insert into T_BRAND (ID, NAME) values ('BRD00040', 'JBL');
insert into T_BRAND (ID, NAME) values ('BRD00041', 'KASPERSKY');
insert into T_BRAND (ID, NAME) values ('BRD00042', 'KINGSTON');
insert into T_BRAND (ID, NAME) values ('BRD00043', 'LENOVO');
insert into T_BRAND (ID, NAME) values ('BRD00044', 'LG - ELECTRONICS');
insert into T_BRAND (ID, NAME) values ('BRD00045', 'LOGITECH');
insert into T_BRAND (ID, NAME) values ('BRD00046', 'MICROSOFT');
insert into T_BRAND (ID, NAME) values ('BRD00047', 'MSI');
insert into T_BRAND (ID, NAME) values ('BRD00048', 'MOTOROLA');
insert into T_BRAND (ID, NAME) values ('BRD00049', 'NOKIA');
insert into T_BRAND (ID, NAME) values ('BRD00050', 'QNAP');
insert into T_BRAND (ID, NAME) values ('BRD00051', 'REDRAGON');
insert into T_BRAND (ID, NAME) values ('BRD00052', 'SAMSUNG');
insert into T_BRAND (ID, NAME) values ('BRD00053', 'SANDISK');
insert into T_BRAND (ID, NAME) values ('BRD00054', 'SEAGATE');
insert into T_BRAND (ID, NAME) values ('BRD00055', 'SONY');
insert into T_BRAND (ID, NAME) values ('BRD00056', 'TARGUS');
insert into T_BRAND (ID, NAME) values ('BRD00057', 'TEROS');
insert into T_BRAND (ID, NAME) values ('BRD00058', 'TOSHIBA');
insert into T_BRAND (ID, NAME) values ('BRD00059', 'TP-LINK');
insert into T_BRAND (ID, NAME) values ('BRD00060', 'XIAOMI');

insert into T_CATEGORY (ID, LABEL, NAME) values ('CAT00001', 'NBK', 'NOTEBOOKS LAPTOPS PORTATILES');
insert into T_CATEGORY (ID, LABEL, NAME) values ('CAT00002', 'NBAC', 'ACCESORIOS DE NOTEBOOK');
insert into T_CATEGORY (ID, LABEL, NAME) values ('CAT00003', 'BB', 'COMPUTADORAS DESKTOP');
insert into T_CATEGORY (ID, LABEL, NAME) values ('CAT00004', 'PDA', 'TABLETS / LENTES VR / CALCULADORAS');
insert into T_CATEGORY (ID, LABEL, NAME) values ('CAT00005', 'TC', 'TELEFONOS CELULARES');
insert into T_CATEGORY (ID, LABEL, NAME) values ('CAT00006', 'MBD', 'MOTHERBOARDS (PLACAS BASE)');
insert into T_CATEGORY (ID, LABEL, NAME) values ('CAT00007', 'CPU', 'CPUS (MICROPROCESADORES)');
insert into T_CATEGORY (ID, LABEL, NAME) values ('CAT00008', 'CPX', 'COOLER Y ADAPTADOR DE CPU');
insert into T_CATEGORY (ID, LABEL, NAME) values ('CAT00009', 'MEM', 'MEMORIAS RAM');
insert into T_CATEGORY (ID, LABEL, NAME) values ('CAT00010', 'HDE', 'DISCOS DUROS EXTERNOS');
insert into T_CATEGORY (ID, LABEL, NAME) values ('CAT00011', 'HD', 'DISCOS DUROS INTERNOS');
insert into T_CATEGORY (ID, LABEL, NAME) values ('CAT00012', 'HDES', 'DISCOS DUROS SOLIDOS INTERNOS');
insert into T_CATEGORY (ID, LABEL, NAME) values ('CAT00013', 'HDX', 'ACCESORIOS DE DISCOS DUROS');
insert into T_CATEGORY (ID, LABEL, NAME) values ('CAT00014', 'VID', 'TARJETAS DE VIDEO / DISPOSITIVOS DE VIDEO');
insert into T_CATEGORY (ID, LABEL, NAME) values ('CAT00015', 'VIG', 'ACCESORIOS DE TARJETAS DE VIDEO');
insert into T_CATEGORY (ID, LABEL, NAME) values ('CAT00016', 'CD', 'CDROM / DVD / BLU RAY DRIVES');
insert into T_CATEGORY (ID, LABEL, NAME) values ('CAT00017', 'AUD', 'AUDIO');
insert into T_CATEGORY (ID, LABEL, NAME) values ('CAT00018', 'CSE', 'CASES (CAJAS) PARA PC');
insert into T_CATEGORY (ID, LABEL, NAME) values ('CAT00019', 'CSX', 'ACCESORIOS DE CASES');
insert into T_CATEGORY (ID, LABEL, NAME) values ('CAT00020', 'PSCS', 'FUENTE PARA CASES');
insert into T_CATEGORY (ID, LABEL, NAME) values ('CAT00021', 'MON', 'MONITORES');
insert into T_CATEGORY (ID, LABEL, NAME) values ('CAT00022', 'MOAC', 'ACCESORIOS DE MONITORES');
insert into T_CATEGORY (ID, LABEL, NAME) values ('CAT00023', 'TEL', 'TELEVISORES');
insert into T_CATEGORY (ID, LABEL, NAME) values ('CAT00024', 'MI', 'MOUSE, TRACKBALL, PUNTEROS');
insert into T_CATEGORY (ID, LABEL, NAME) values ('CAT00025', 'MSS', 'DISPOSITIVOS DE IMAGENES');
insert into T_CATEGORY (ID, LABEL, NAME) values ('CAT00026', 'PR', 'IMPRESORAS');
insert into T_CATEGORY (ID, LABEL, NAME) values ('CAT00027', 'PRAC', 'ACCESORIOS DE IMPRESORAS');
insert into T_CATEGORY (ID, LABEL, NAME) values ('CAT00028', 'MC', 'MEMORIAS FLASH');
insert into T_CATEGORY (ID, LABEL, NAME) values ('CAT00029', 'NW', 'PRODUCTOS DE REDES LAN/WAN');
insert into T_CATEGORY (ID, LABEL, NAME) values ('CAT00030', 'NWL', 'REDES INALAMBRICAS');
insert into T_CATEGORY (ID, LABEL, NAME) values ('CAT00031', 'MSLV', 'LICENCIAS VIRTUALES DE MICROSOFT');
insert into T_CATEGORY (ID, LABEL, NAME) values ('CAT00032', 'MSSW', 'O/S SOFTWARE DE MICROSOFT');
insert into T_CATEGORY (ID, LABEL, NAME) values ('CAT00033', 'ACC', 'ACCESORIOS / MISCELANEOS');
insert into T_CATEGORY (ID, LABEL, NAME) values ('CAT00034', '0000', 'SIN CLASIFICAR / VARIOS');
insert into T_CATEGORY (ID, LABEL, NAME) values ('CAT00035', 'ST', 'SUMINISTROS');
insert into T_CATEGORY (ID, LABEL, NAME) values ('CAT00036', 'VIJ', 'CONSOLAS PARA VIDEOJUEGOS');
insert into T_CATEGORY (ID, LABEL, NAME) values ('CAT00037', 'PS', 'UPS / ESTABILIZADORES / ACCESORIOS DE UPS');
insert into T_CATEGORY (ID, LABEL, NAME) values ('CAT00038', 'PDAA', 'ACCESORIOS DE TABLETS');
insert into T_CATEGORY (ID, LABEL, NAME) values ('CAT00039', 'BM', 'BAREBONES');
insert into T_CATEGORY (ID, LABEL, NAME) values ('CAT00040', 'KB', 'TECLADOS');

insert into T_PRODUCT (NAME, PRICE, CATEGORY_ID, BRAND_ID) VALUES ('Notebook HP 250 G9, 15.6" LCD HD SVA, Celeron N4500 1.10/2.8GHz, 8GB DDR4-2933MHz SODIMM', 1990.00, 'CAT00001', 'BRD00037');
insert into T_PRODUCT (NAME, PRICE, CATEGORY_ID, BRAND_ID) VALUES ('Notebook Lenovo V15 G2 IJL, 15.6" FHD TN, Celeron N4500 1.1/2.8GHz, 8GB DDR4-2933MHz', 2190.90, 'CAT00001', 'BRD00043');
insert into T_PRODUCT (NAME, PRICE, CATEGORY_ID, BRAND_ID) VALUES ('Notebook Advance Nova Nv9801, 10.1", Intel Atom Z8350 1.44GHz, 2GB DDR3, 32GB eMMC', 1800.99, 'CAT00001', 'BRD00002');
insert into T_PRODUCT (NAME, PRICE, CATEGORY_ID, BRAND_ID) VALUES ('Notebook ASUS X1504VA-NJ946, 15.6" LED FHD 16:9, 60Hz, Core i3-100U 1.2/4.7GHz, 8GB DDR4 ', 2780.99, 'CAT00001', 'BRD00011');
insert into T_PRODUCT (NAME, PRICE, CATEGORY_ID, BRAND_ID) VALUES ('Notebook ASUS X1504VA-NJ946, 15.6" LED FHD 16:9, 60Hz, Core i3-100U 1.2/4.7GHz, 8GB DDR4 ', 2780.99, 'CAT00001', 'BRD00011');